//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlifSani.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class BeneficiaryAccount
    {
        public int Id { get; set; }
        public string AccountTitle { get; set; }
        public string AccountNo { get; set; }
        public string Bank { get; set; }
        public string Branch { get; set; }
        public string BranchCode { get; set; }
        public string Address { get; set; }
        public string SwiftCode { get; set; }
        public string Phone { get; set; }
        public string UAN { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public bool Status { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
