//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlifSani.Models.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AuditReport> AuditReports { get; set; }
        public virtual DbSet<BeneficiaryAccount> BeneficiaryAccounts { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<DonateCustomerInfo> DonateCustomerInfoes { get; set; }
        public virtual DbSet<DonationCategory> DonationCategories { get; set; }
        public virtual DbSet<DonationItem> DonationItems { get; set; }
        public virtual DbSet<Download> Downloads { get; set; }
        public virtual DbSet<FutureProject> FutureProjects { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<PhotoAlbumImage> PhotoAlbumImages { get; set; }
        public virtual DbSet<PhotoAlbum> PhotoAlbums { get; set; }
        public virtual DbSet<PhotoGallery> PhotoGalleries { get; set; }
        public virtual DbSet<PhotoSlider> PhotoSliders { get; set; }
        public virtual DbSet<PressRelease> PressReleases { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<TaxDoc> TaxDocs { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<VideoGallery> VideoGalleries { get; set; }
    }
}
