//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlifSani.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhotoAlbum
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhotoAlbum()
        {
            this.PhotoAlbumImages = new HashSet<PhotoAlbumImage>();
        }
    
        public int Id { get; set; }
        public string AlbumName { get; set; }
        public string AlbumDescription { get; set; }
        public string Thumbnail { get; set; }
        public bool Status { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhotoAlbumImage> PhotoAlbumImages { get; set; }
    }
}
